#!/bin/sh

set -e

count=1;
for file in $(find t -name \*.t.js); do
  node_modules/.bin/istanbul cover -x 't/**' $file > /dev/null 2>&1
  mv coverage/coverage.json coverage/coverage$count.json
  count=$(expr $count + 1)
done

cp convertLcovToCoveralls.js node_modules/coveralls/lib

node_modules/.bin/istanbul report --root coverage --dir coverage  --format lcovonly  

exit 0
