#!/bin/bash

printf "    %-24s %11s %11s %11s %11s\n" File Raw Min Zip Min/Zip
for file in $@; do
  b_raw=$(cat $file | wc -c)
  b_min=$(cat $file | uglifyjs | wc -c)
  alt=$(cat $file | uglifyjs --lift-vars | wc -c)
  if [ $alt -lt ${b_min} ]; then
    b_min=$alt
  fi
  b_zip=$(cat $file | gzip -c  | wc -c)
  b_minzip=$(cat $file | uglifyjs | gzip -c | wc -c)
  alt=$(cat $file | uglifyjs --lift-vars | gzip -c | wc -c)
  if [ $alt -lt ${b_minzip} ]; then
    b_minzip=$alt
  fi
  printf "    %-24s" $file
  for field in raw min zip minzip; do
    key="b_${field}"
    value=$(echo "${!key} / 1024" | bc -l)
    printf "%6d/%05.2f" ${!key} ${value}
  done
  printf "\n"
done
