#!/bin/sh

dir=`cd ${0%/*} && pwd`

printf "%-24s %11s %11s %11s %11s\n" File Raw Min Zip Min/Zip
for file in $@; do
  b_0=`cat $file | wc -c`
  b_1=`cat $file | uglifyjs | wc -c`
  b_2=`cat $file | gzip -c  | wc -c`
  b_3=`cat $file | uglifyjs | gzip -c | wc -c`
  for field in 0 1 2 3; do
    eval val=\$b_$field
    val=`awk -v val="$val" 'BEGIN { printf "%.2f", val / 1024 }'`
    eval k_$field=$val
  done
  printf "%-24s" $file
  for field in 0 1 2 3; do
    eval printf "%6d/%05.2f" \$b_$field \$k_$field
  done
  printf "\n"
done
