#!/bin/sh

set -e

if [ "$TRAVIS" = "true" ]; then
  echo '$ sudo apt-get install bc' && echo ''
  sudo apt-get install -q -q bc 2> /dev/null > /dev/null
fi

t/sizes index.js | sed 's/^/    /'

echo ""

(proof run t/*/*.t.js | tee .proof.out | proof progress) || (proof errors < .proof.out) || exit 1

if [ "$TRAVIS" = "true" ] || [ "$MINIFY" = "true" ]; then
  echo "generating coverage"
  t/cover

  echo "submitting coverage to coveralls.io"
  cat coverage/lcov.info | node_modules/.bin/coveralls

  echo '[default]' > ~/.s3cfg
  chmod 600 ~/.s3cfg
  echo "access_key = $ARTIFACTS_AWS_ACCESS_KEY_ID" >> ~/.s3cfg
  echo "secret_key = $ARTIFACTS_AWS_SECRET_ACCESS_KEY" >> ~/.s3cfg
  export AWS_SECRET_ACCESS_KEY=$AWS_ACCESS_KEY_ID
  export ARTIFACTS_AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  echo s3sync './coverage/' 's3://bigeasy/coverage/cadence/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID/'
  sed -i "1s/^/require 'delegate'/" ~/.rvm/gems/ruby*/gems/s3sync*/lib/HTTPStreaming.rb
  s3sync --verbose './coverage/' 's3://bigeasy/coverage/cadence/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID/'

  echo ""
  echo "minified"
  echo ""
  default=$(cat index.js | uglifyjs | gzip -c | wc -c)
  lift=$(cat index.js | uglifyjs --lift-vars | gzip -c | wc -c)

  bak=index-$(date +'%FT%T').js
  mv index.js $bak
  if [ $default -lt $lift ]; then
    cat $bak | uglifyjs > index.js
  else
    cat $bak | uglifyjs --lift-vars > index.js
  fi

  (proof run t/*/*.t.js | tee .proof.out | proof progress) || (proof errors < .proof.out) || exit 1
fi

echo ""
