#!/bin/sh

set -e

t/sizes cadence.js | sed 's/^/    /'

echo ""

(proof run t/*.t.js | tee .proof.out | proof progress) \
    || (proof errors < .proof.out) \
    || exit 1

if [ "$TRAVIS" = "true" ] || [ "$MINIFY" = "true" ]; then
  # note: do not `--lift-vars` because it ruins arity functions by eliminating
  # unused function vars.
  echo ""
  echo "minified"
  echo ""
  bak=cadence-$(date +'%FT%T' | tr ':' '-').js
  mv cadence.js $bak
  cat $bak | uglifyjs > cadence.js
  (proof run t/*.t.js | tee .proof.out | proof progress) \
        || (proof errors < .proof.out) \
        || exit 1
  cp $bak cadence.js
fi

if [ "$TRAVIS" = "true" ]; then
  echo ""
  echo "running with coverage"
  t/cover
  istanbul report --format text
  echo ""

  echo "submitting to coveralls.io"
  (cat coverage/lcov.info | coveralls) > /dev/null 2>&1
fi

echo ""
